---
environments:
  - name: env-1
    secrets:
      - name: AWS_ACCESS_KEY_ID
        secret: op://Private/AWS/access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        secret: op://Private/AWS/secret_access_key

    values:
      - name: AWS_REGION
        value: eu-central-1

  - name: env-2
    aws_sts_configs:
      - access_key_id: op://Private/AWS/access_key_id
        secret_access_key: op://Private/AWS/secret_access_key
        role_arn: arn:aws:iam::012345678910:role/admin
