= 1PENRC(5)
Felix Ehrenpfort
:doctype: manpage
:source-highlighter: rouge

== NAME

~/.config/1penrc.hcl - configuration file for 1penrc

== DESCRIPTION

1penrc uses a configuration file to declare how an items fields are being exported and which items belong to
the same _environment_ and should be exported together.

1penrc uses HCL (HashiCorp Configuration Language) as it's configuration file syntax with the following information
model.

At the top-level the configuration file consists of multiple _environment_ blocks that are used to group 1Password
items together.

=== ENVIRONMENT

Each environment has a _name_ label as well as one or more _item_ blocks.
The _name_ of the environment is used to refer to this group on the CLI, e.g., exporting an environments variables.

[source,hcl]
----
env "<name>" {}
----

==== Attributes

extra::

A string map of additional variables being exported, where the key is a variable name and value a variables value.

=== ITEM

The item block defines which and how fields of a 1Password item are used as variable values.
Which 1Password item is being used is declared via the _account_ and _reference_ label, where
_account_ is an op account shorthand name and _reference_ can be a UUID, name or domain.
How an items fields are being exported as environment variables is done via the _supplier_ declared in the _supplier_
label.
I.e., the _static supplier_ defines a mapping of variable names to an items field names.

[source,hcl]
----
item "<supplier>" "<account>" "<reference>" {}
----

=== SUPPLIER STATIC

The _static_ supplier is the most basic of all suppliers as it only defines a mapping between item fields and
variable names.

==== Attributes

mapping::
A string map where the keys are the variables names and the values are names of the fields being exported.

== FILES

_~/.config/1penrc.hcl_::
Default configuration file.

== EXAMPLE

The following example configuration file defines an environment called _example.com_ with a single item and
extra variables.
The _example.com_ environment exports the _API_TOKEN_ and _API_URL_ variables where the former gets it's value from a
field called _api_token_ of item _0123456789_ inside _my_ account.

[source,hcl]
----
env "example.com" {
  item "static" "my" "0123456789" {
    mapping = {
      API_TOKEN = "api_token"
    }
  }

  extra {
    API_URL = "https://api.example.com"
  }
}
----

== SEE ALSO

*1penrc(1)*
